---
- name: 'Converge'
  hosts: 'all'
  vars:
    motd_host_function: 'Molecule test system'
  tasks:
    - name: 'Run role'
      ansible.builtin.import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
